# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
exporters:
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "http://fleet-server:8200"
    tls:
      insecure: true
      insecure_skip_verify: true
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    logs: 
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
